use std::path::{Path, PathBuf};
use std::process::Command;

const WASM_CRATES: &[(&str, &str)] = &[
    (
        "migration-fixtures/stealth-sender-v0",
        "stealth_sender_v0",
    ),
    ("migration-fixtures/wraith-names-v0", "wraith_names_v0"),
    (
        "migration-fixtures/stealth-registry-v0",
        "stealth_registry_v0",
    ),
    ("stealth-sender", "stealth_sender"),
    ("wraith-names", "wraith_names"),
    ("stealth-registry", "stealth_registry"),
];

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("upgrade-migration-tests must live under stellar/")
        .to_path_buf()
}

fn build_wasm(manifest: &Path) {
    let status = Command::new("cargo")
        .arg("build")
        .arg("--release")
        .arg("--target")
        .arg("wasm32-unknown-unknown")
        .arg("--manifest-path")
        .arg(manifest)
        .status()
        .unwrap_or_else(|e| panic!("failed to spawn cargo build for {}: {e}", manifest.display()));

    assert!(
        status.success(),
        "wasm build failed for {}",
        manifest.display()
    );
}

fn main() {
    let root = workspace_root();
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let release_wasm = root.join("target/wasm32-unknown-unknown/release");

    let mut manifest_lines = String::from("// @generated by upgrade-migration-tests/build.rs\n");

    for (crate_path, stem) in WASM_CRATES {
        let manifest = root.join(crate_path).join("Cargo.toml");
        println!("cargo:rerun-if-changed={}", manifest.display());
        let src_dir = root.join(crate_path).join("src");
        if src_dir.is_dir() {
            println!("cargo:rerun-if-changed={}", src_dir.display());
        }

        build_wasm(&manifest);

        let wasm_src = release_wasm.join(format!("{stem}.wasm"));
        assert!(
            wasm_src.is_file(),
            "expected wasm artifact at {}",
            wasm_src.display()
        );

        let wasm_dst = out_dir.join(format!("{stem}.wasm"));
        std::fs::copy(&wasm_src, &wasm_dst).unwrap_or_else(|e| {
            panic!(
                "copy {} -> {}: {e}",
                wasm_src.display(),
                wasm_dst.display()
            )
        });

        manifest_lines.push_str(&format!(
            "pub const {}: &[u8] = include_bytes!(\"{stem}.wasm\");\n",
            stem.to_uppercase()
        ));
    }

    std::fs::write(out_dir.join("wasm_manifest.rs"), manifest_lines).unwrap();
}
