[workspace]
members = [
  "stealth-announcer",
  "stealth-registry",
  "stealth-sender",
  "stealth-splitter",
  "stealth-batch-sender",
  "wraith-names",
  "bench",
  "wraith-asset-policy",
  "wraith-metrics",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = "22.0.0"

[profile.release]
opt-level = "z"
strip = "debuginfo"
lto = true
codegen-units = 1
panic = "abort"
