[package]
name = "wraith-stellar-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
stealth-announcer = { path = "../stealth-announcer" }
stealth-registry = { path = "../stealth-registry" }
stealth-sender = { path = "../stealth-sender" }
wraith-names = { path = "../wraith-names" }

[[bench]]
name = "gas"
harness = false
