//! Pure-Rust reference implementation of the StealthRegistry contract.
//!
//! This module provides a normative, executable specification of the
//! stealth-registry contract's semantics. Every behaviour described here
//! MUST match the on-chain contract byte-for-byte. When the on-chain
//! contract diverges, this reference implementation is authoritative
//! (i.e., the contract has a bug).
//!
//! ## Modeled Semantics
//!
//! - **Register:** Stores a 64-byte meta-address keyed by (registrant, scheme_id).
//!   Overwrites any existing entry. Extends the entry's TTL to `TTL_EXTEND_TO`
//!   from the current ledger sequence.
//! - **Revoke (Remove):** Deletes the entry for (registrant, scheme_id).
//!   Returns `NotRegistered` if the entry does not exist or has expired.
//! - **Expire:** Entries whose TTL has elapsed become inaccessible. Accessing an
//!   entry via register or lookup extends its TTL (but only when the remaining
//!   TTL has dropped below the `TTL_THRESHOLD`). The `AdvanceLedger` operation
//!   models the passage of ledger sequences that triggers expiration.
//! - **Re-register:** Identical to Register; overwrites any existing entry and
//!   resets its TTL.
//!
//! ## TTL Model
//!
//! Every entry tracks an `expires_at` ledger. On `register_keys` the entry
//! expires at `current_ledger + TTL_EXTEND_TO`. On `stealth_meta_address_of`,
//! if the remaining TTL is below `TTL_THRESHOLD`, the entry is extended to
//! `current_ledger + TTL_EXTEND_TO`. This mirrors Soroban's `extend_ttl`
//! semantics.
//!
//! ## Events
//!
//! The reference tracks only the application-level events (register, remove).
//! Metric events (wraith-metrics) are excluded because they are an orthogonal
//! observability concern that the differential test filters out on the
//! on-chain side.

use std::collections::HashMap;

/// Number of simulated addresses available for registrants.
pub const NUM_REGISTRANTS: usize = 8;

/// TTL constants matching the on-chain contract.
const TTL_THRESHOLD: u32 = 17280; // ~1 day of ledgers
const TTL_EXTEND_TO: u32 = 518400; // ~30 days of ledgers

// ---------------------------------------------------------------------------
// Operation & result types
// ---------------------------------------------------------------------------

/// An operation that can be performed on the registry.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Op {
    /// Register or update a meta-address for (registrant, scheme_id).
    Register {
        registrant: u8,
        scheme_id: u32,
        meta: [u8; 64],
    },
    /// Remove a previously registered meta-address.
    Remove {
        registrant: u8,
        scheme_id: u32,
    },
    /// Look up a registered meta-address.
    Lookup {
        registrant: u8,
        scheme_id: u32,
    },
    /// Advance the ledger by `count` sequences.
    /// Simulates TTL-based expiration of storage entries.
    AdvanceLedger {
        count: u32,
    },
}

/// The result of attempting an operation.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum OpResult {
    /// The operation succeeded and registered/updated a meta-address.
    Registered([u8; 64]),
    /// The operation succeeded and removed an entry.
    Removed,
    /// The operation succeeded and returned the looked-up meta-address.
    LookupValue([u8; 64]),
    /// The ledger was advanced (AdvanceLedger).
    LedgerAdvanced,
    /// The meta-address was not exactly 64 bytes (register).
    /// Not generated by the differential test's proptest strategy (which
    /// always emits 64-byte values) but included for completeness.
    /// Length validation is covered by `properties.rs`.
    #[allow(dead_code)]
    InvalidMetaAddressLength,
    /// The entry was not found / has expired (lookup, remove).
    NotRegistered,
}

/// Application-level events emitted by the registry.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RefEvent {
    Register {
        registrant: u8,
        scheme_id: u32,
        meta: [u8; 64],
    },
    Remove {
        registrant: u8,
        scheme_id: u32,
    },
}

// ---------------------------------------------------------------------------
// Internal entry state
// ---------------------------------------------------------------------------

/// Internal state for a single registry entry.
#[derive(Clone, Debug)]
struct Entry {
    meta: [u8; 64],
    /// Ledger sequence at which this entry expires.
    expires_at: u32,
}

// ---------------------------------------------------------------------------
// ReferenceRegistry
// ---------------------------------------------------------------------------

/// Pure-Rust reference implementation of the StealthRegistry contract.
///
/// Tracks registrations and models Soroban TTL semantics faithfully.
/// This is the normative specification for expected on-chain behavior.
#[derive(Clone, Debug)]
pub struct ReferenceRegistry {
    entries: HashMap<(u8, u32), Entry>,
    ledger: u32,
    events: Vec<RefEvent>,
}

impl Default for ReferenceRegistry {
    fn default() -> Self {
        Self {
            entries: HashMap::new(),
            ledger: 0,
            events: Vec::new(),
        }
    }
}

impl ReferenceRegistry {
    /// Create a new reference registry starting at ledger 0.
    pub fn new() -> Self {
        Self::default()
    }

    /// Apply an operation and return the result.
    ///
    /// Side effects:
    /// - Application-level events are appended to the internal event log.
    /// - Storage entries are created, updated, or deleted.
    /// - TTLs are extended as described in the module documentation.
    pub fn apply(&mut self, op: &Op) -> OpResult {
        match op {
            Op::Register {
                registrant,
                scheme_id,
                meta,
            } => {
                let key = (*registrant, *scheme_id);
                self.entries.insert(
                    key,
                    Entry {
                        meta: *meta,
                        expires_at: self.ledger + TTL_EXTEND_TO,
                    },
                );
                self.events.push(RefEvent::Register {
                    registrant: *registrant,
                    scheme_id: *scheme_id,
                    meta: *meta,
                });
                OpResult::Registered(*meta)
            }
            Op::Remove {
                registrant,
                scheme_id,
            } => {
                let key = (*registrant, *scheme_id);
                // Check if entry exists and is not expired.
                match self.entries.get(&key) {
                    Some(entry) if self.ledger < entry.expires_at => {
                        self.entries.remove(&key);
                        self.events.push(RefEvent::Remove {
                            registrant: *registrant,
                            scheme_id: *scheme_id,
                        });
                        OpResult::Removed
                    }
                    _ => {
                        // Entry either never existed or has expired.
                        // Clean up stale entry if present.
                        self.entries.remove(&key);
                        OpResult::NotRegistered
                    }
                }
            }
            Op::Lookup {
                registrant,
                scheme_id,
            } => {
                let key = (*registrant, *scheme_id);
                match self.entries.get(&key) {
                    Some(entry) if self.ledger < entry.expires_at => {
                        let meta = entry.meta;
                        // Extend TTL if below threshold (modeling extend_ttl).
                        let remaining = entry.expires_at.saturating_sub(self.ledger);
                        if remaining < TTL_THRESHOLD {
                            self.entries.insert(
                                key,
                                Entry {
                                    meta,
                                    expires_at: self.ledger + TTL_EXTEND_TO,
                                },
                            );
                        }
                        OpResult::LookupValue(meta)
                    }
                    _ => {
                        // Clean up expired entry.
                        self.entries.remove(&key);
                        OpResult::NotRegistered
                    }
                }
            }
            Op::AdvanceLedger { count } => {
                self.ledger += count;
                OpResult::LedgerAdvanced
            }
        }
    }

    /// Query the current state for a (registrant, scheme_id) pair.
    ///
    /// Returns `Some(meta)` if the entry is registered and has not expired,
    /// or `None` otherwise. This is a read-only operation that does NOT
    /// extend TTL (unlike `stealth_meta_address_of`).
    pub fn get(&self, registrant: u8, scheme_id: u32) -> Option<[u8; 64]> {
        let key = (registrant, scheme_id);
        self.entries.get(&key).and_then(|entry| {
            if self.ledger < entry.expires_at {
                Some(entry.meta)
            } else {
                None
            }
        })
    }

    /// Look up a stealth meta-address with TTL extension semantics.
    ///
    /// Mirrors the on-chain `stealth_meta_address_of`:
    /// - Returns `Some(meta)` if the entry exists and has not expired.
    /// - If the remaining TTL is below `TTL_THRESHOLD`, extends it to
    ///   `current_ledger + TTL_EXTEND_TO` (matching `extend_ttl`).
    /// - Returns `None` if the entry does not exist or has expired.
    /// - Does NOT emit any events (lookups are read-only).
    pub fn stealth_meta_address_of(
        &mut self,
        registrant: u8,
        scheme_id: u32,
    ) -> Option<[u8; 64]> {
        let key = (registrant, scheme_id);
        match self.entries.get(&key) {
            Some(entry) if self.ledger < entry.expires_at => {
                let meta = entry.meta;
                let remaining = entry.expires_at.saturating_sub(self.ledger);
                if remaining < TTL_THRESHOLD {
                    self.entries.insert(
                        key,
                        Entry {
                            meta,
                            expires_at: self.ledger + TTL_EXTEND_TO,
                        },
                    );
                }
                Some(meta)
            }
            _ => {
                // Clean up expired entry.
                self.entries.remove(&key);
                None
            }
        }
    }

    /// Return the application-level events emitted so far.
    pub fn events(&self) -> &[RefEvent] {
        &self.events
    }

}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_register_then_lookup() {
        let mut r = ReferenceRegistry::new();
        let meta = [42u8; 64];

        let result = r.apply(&Op::Register {
            registrant: 0,
            scheme_id: 1,
            meta,
        });
        assert_eq!(result, OpResult::Registered(meta));

        let result = r.apply(&Op::Lookup {
            registrant: 0,
            scheme_id: 1,
        });
        assert_eq!(result, OpResult::LookupValue(meta));
        assert_eq!(r.get(0, 1), Some(meta));
    }

    #[test]
    fn test_remove() {
        let mut r = ReferenceRegistry::new();
        let meta = [99u8; 64];

        r.apply(&Op::Register {
            registrant: 1,
            scheme_id: 2,
            meta,
        });
        assert_eq!(r.get(1, 2), Some(meta));

        let result = r.apply(&Op::Remove {
            registrant: 1,
            scheme_id: 2,
        });
        assert_eq!(result, OpResult::Removed);
        assert_eq!(r.get(1, 2), None);
    }

    #[test]
    fn test_remove_not_registered() {
        let mut r = ReferenceRegistry::new();
        let result = r.apply(&Op::Remove {
            registrant: 3,
            scheme_id: 7,
        });
        assert_eq!(result, OpResult::NotRegistered);
    }

    #[test]
    fn test_lookup_not_registered() {
        let mut r = ReferenceRegistry::new();
        let result = r.apply(&Op::Lookup {
            registrant: 0,
            scheme_id: 0,
        });
        assert_eq!(result, OpResult::NotRegistered);
    }

    #[test]
    fn test_re_register_overwrites() {
        let mut r = ReferenceRegistry::new();
        let first = [1u8; 64];
        let second = [2u8; 64];

        r.apply(&Op::Register {
            registrant: 0,
            scheme_id: 0,
            meta: first,
        });
        r.apply(&Op::Register {
            registrant: 0,
            scheme_id: 0,
            meta: second,
        });

        assert_eq!(r.get(0, 0), Some(second));
    }

    #[test]
    fn test_events_tracked() {
        let mut r = ReferenceRegistry::new();
        let meta = [7u8; 64];

        r.apply(&Op::Register {
            registrant: 2,
            scheme_id: 5,
            meta,
        });
        r.apply(&Op::Remove {
            registrant: 2,
            scheme_id: 5,
        });

        let events = r.events();
        assert_eq!(events.len(), 2);
        assert_eq!(
            events[0],
            RefEvent::Register {
                registrant: 2,
                scheme_id: 5,
                meta,
            }
        );
        assert_eq!(
            events[1],
            RefEvent::Remove {
                registrant: 2,
                scheme_id: 5,
            }
        );
    }

    #[test]
    fn test_expiry_after_advance() {
        let mut r = ReferenceRegistry::new();
        let meta = [0xabu8; 64];

        // Register at ledger 0: expires at 518400.
        r.apply(&Op::Register {
            registrant: 0,
            scheme_id: 1,
            meta,
        });
        assert_eq!(r.get(0, 1), Some(meta));

        // Advance past TTL: entry should be gone.
        r.apply(&Op::AdvanceLedger {
            count: TTL_EXTEND_TO + 1,
        });
        assert_eq!(r.get(0, 1), None);
    }

    #[test]
    fn test_lookup_extends_ttl_when_below_threshold() {
        let mut r = ReferenceRegistry::new();
        let meta = [0xcd; 64];

        // Register at ledger 0.
        r.apply(&Op::Register {
            registrant: 0,
            scheme_id: 0,
            meta,
        });

        // Advance to just below the threshold (so remaining TTL is below threshold).
        r.apply(&Op::AdvanceLedger {
            count: TTL_EXTEND_TO - TTL_THRESHOLD + 1,
        });
        // At this point: ledger ≈ 501121, remaining ≈ 17279 < threshold (17280).
        // A lookup should extend TTL.

        assert_eq!(r.get(0, 0), Some(meta)); // Still alive.

        r.apply(&Op::Lookup {
            registrant: 0,
            scheme_id: 0,
        });

        // The TTL was extended. Advance again; the entry should still be alive
        // for another ~TTL_EXTEND_TO ledgers.
        r.apply(&Op::AdvanceLedger {
            count: TTL_THRESHOLD + 100,
        });
        assert_eq!(
            r.get(0, 0),
            Some(meta),
            "entry should still be alive after TTL extension"
        );
    }

    #[test]
    fn test_independent_scheme_ids() {
        let mut r = ReferenceRegistry::new();
        let m1 = [1u8; 64];
        let m2 = [2u8; 64];

        r.apply(&Op::Register {
            registrant: 0,
            scheme_id: 1,
            meta: m1,
        });
        r.apply(&Op::Register {
            registrant: 0,
            scheme_id: 2,
            meta: m2,
        });

        assert_eq!(r.get(0, 1), Some(m1));
        assert_eq!(r.get(0, 2), Some(m2));

        r.apply(&Op::Remove {
            registrant: 0,
            scheme_id: 1,
        });

        assert_eq!(r.get(0, 1), None);
        assert_eq!(r.get(0, 2), Some(m2)); // Independent
    }
}
